export const metadata = {
  title: "Sign in to your Telstra ID",
  description: "Generated by create next app",
  icons: {
    icon: '/embedded-svg-001.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0, fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif' }}>
        {children}
      </body>
    </html>
  );
}
